config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"
  get '/account', to: 'account#show'
  get '/reservations/confirm', to: 'reservations#index'
  resources :reservations
  resources :rooms do
    collection do
      get 'search', to: 'rooms#search'
    end
  end
  devise_for :users
  resources :rooms
  get 'accounts/show'
  resources :users
  resource :account, only: [:edit, :update, :show]
  get '/account', to: 'accounts#show'
  get '/users', to: 'users#show'
  get '/rooms', to: 'rooms#new'
  post '/rooms', to: 'rooms#update'
  get '/reservations/confirm', to: 'reservations#confirm', as: 'confirm_reservation'
  post '/reservations/confirm', to: 'reservations#confirm'
  get '/rooms/search', to: 'rooms#search'

  resources :reservations, only: [:index, :new, :create, :show] do
    collection do
      post 'confirm'
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :check_in, presence: { message: "チェックイン日を入力してください" }
  validates :check_out, presence: { message: "チェックアウト日を入力してください" }
  validate :check_out_after_check_in
  validates :number_of_people, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def total_days
    (check_out - check_in).to_i
  end

  def total_price
    room = Room.find(room_id)
    total_days * number_of_people.to_i * room.price.to_i
  end

  validate :check_out_after_check_in

  def check_out_after_check_in
    if check_in.present? && check_out.present? && check_out <= check_in
      errors.add(:check_out, "はチェックイン日より後の日付にしてください")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
    @user = current_user
    @reservation = @user.rooms
  end

  def new
    @room = Room.find(params[:room_id])
    @reservation = @room.reservations.new
    @reservation.user_id = current_user.id 
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @room = Room.find(params[:reservation][:room_id])
    @reservation.room_id = @room.id
    if @reservation.save
      redirect_to reservations_path, notice: 'Reservation was successfully created.'
    else
      render "rooms/show"
    end
  end

  def update
    @reservation = Reservation.new(reservation_params)
  end

  def show
    @reservations = Reservation.all

    if @reservation.nil?
      flash[:error] = '予約情報が見つかりませんでした。'
      redirect_to root_path and return
    end

    @room = @reservation.room
    if @room.nil?
      flash[:error] = '部屋情報が見つかりませんでした。'
      redirect_to root_path and return
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @room = @reservation.room
  end

  def confirm
    @reservation = Reservation.new(reservation_params)
    @room = Room.find(params[:reservation][:room_id])
    @user_id = current_user.id
    @check_in = @reservation.check_in
    @check_out = @reservation.check_out

    if @reservation.check_in.nil?
      redirect_to @room, alert: "開始日を入力してください"
      return
    end
    
    if @reservation.check_out.nil?
      redirect_to @room, alert: "終了日を入力してください"
      return
    end

    if @reservation.check_out < @reservation.check_in
      redirect_to @room, alert: "終了日は開始日以降の日付にしてください"
      return
    end

    if @reservation.number_of_people.nil?
      redirect_to @room, alert: "人数を入力してください おそらく０になっています０になっています"
      return
    end
    
    @total_day = (@check_out - @check_in).to_i
    @number_of_people = @reservation.number_of_people
    @total_price = @room.price.to_i * @total_day * @reservation.number_of_people.to_i
  end

  private

  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :number_of_people, :room_id, :user_id)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :check_in %>
    <%= form.date_select :check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.date_select :check_out %>
  </div>

  <div class="field">
    <%= form.label :number_of_people %>
    <%= form.number_field :number_of_people %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/confirm.html.erb
<%= form_with model: @reservation ,url: reservations_path do |f| %>

  <h1>予約確認ページ</h1>
  <table>
    <tr>
      <td>チェックイン日:</td>
      <td><%= @reservation.check_in %></td>
    </tr>
    <tr>
      <td>チェックアウト日:</td>
      <td><%= @reservation.check_out %></td>
    </tr>
    <tr>
      <td>宿泊日数:</td>
      <td><%= @total_day %>日</td>
    </tr>
    <tr>
      <td>人数:</td>
      <td><%= @reservation.number_of_people %></td>
    </tr>
    <tr>
      <td>支払い金額:</td>
      <td><%= @total_price %>円</td>
    </tr>
    <tr>
      <td>金額:</td>
      <!-- 金額の表示方法についての情報が不足しているため、具体的なコードを記載することができません -->
    </tr>
  </table>
  <%= f.hidden_field :check_in, value: @reservation.check_in %>
  <%= f.hidden_field :check_out, value: @reservation.check_out %>
  <%= f.hidden_field :number_of_people, value: @reservation.number_of_people %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.submit "予約する" %>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<%= link_to "もう1度 ログイン画面に戻る場合はこちら", posts_path, style: "font-size: 20px;" %>
<h3>予約済み施設一覧</h3>

<table>
  <thead>
    <tr>
      <th>施設画像</th>
      <th>施設名</th>
      <th>施設詳細</th>
      <th>金額</th>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>予約確定日時</th>
    </tr>
  </thead>
  <tbody>
  <% @reservations.each do |reservation| %>
    <% room = Room.find(reservation.room_id) %>
    <tr>
      <td>
        <% if room.image? %>
            <%= image_tag room.image.url, width: 200 %>
        <% else %>
          <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png' %>
        <% end %>
      </td>
      <td><%= room.name %></td>
      <td><%= room.introduction %></td>
      <td><%= room.price * reservation.number_of_people * (reservation.check_out - reservation.check_in).to_i %>円</td>
      <td><%= reservation.check_in.strftime('%Y/%m/%d') %></td>
      <td><%= reservation.check_out.strftime('%Y/%m/%d') %></td>
      <td><%= reservation.created_at.strftime('%Y/%m/%d %H:%M') %></td>
      
    </tr>
  <% end %>
</tbody>
</table>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Check in:</strong>
  <%= @reservation.check_in %>
</p>

<p>
  <strong>Check out:</strong>
  <%= @reservation.check_out %>
</p>

<p>
  <strong>Number of people:</strong>
  <%= @reservation.number_of_people %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @reservation.room_id %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>