config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"
  get '/account', to: 'account#show'
  get '/reservations/confirm', to: 'reservations#index'
  resources :reservations
  resources :rooms do
    collection do
      get 'search', to: 'rooms#search'
    end
  end
  devise_for :users
  resources :rooms
  get 'accounts/show'
  resources :users
  resource :account, only: [:edit, :update, :show]
  get '/account', to: 'accounts#show'
  get '/users', to: 'users#show'
  get '/rooms', to: 'rooms#new'
  post '/rooms', to: 'rooms#update'
  get '/reservations/confirm', to: 'reservations#confirm', as: 'confirm_reservation'
  post '/reservations/confirm', to: 'reservations#confirm'
  get '/rooms/search', to: 'rooms#search'

  resources :reservations, only: [:index, :new, :create, :show] do
    collection do
      post 'confirm'
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
  has_many :reservations
  validates :name , presence: true 
  validates :address , presence: true
  validates :price , presence: true , numericality: { greater_than_or_equal_to: 0 }
  validates :introduction, presence: true 
  mount_uploader :image, AvatarUploader
  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "id", "introduction", "name", "price", "room_image", "updated_at", "user_id","room_id"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["reservations", "user"]
  end

  def self.search(area, keyword)
    rooms = Room.all

    if area.present?
      rooms = rooms.where("address LIKE ?", "%#{area}%")
    end

    if keyword.present?
      rooms = rooms.where("name LIKE ?", "%#{keyword}%")
    end

    rooms
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @user = current_user
    @rooms = @user.rooms
    @rooms = Room.all
  end

  def new
    @user = current_user
    @room = Room.new
  end

  def create
    @user = current_user
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def show
    @user = current_user.id
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to rooms_path
    else
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  def search
    @results = @q.result(distinct: true)
    @rooms = Room.where(some_condition: true)
  end

  private

  def room_params
    params.require(:room).permit(:name, :introduction, :price, :address, :image, :user_id)
  end

  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>編集</h1>
<%= render 'layouts/error_messages', model: @room %>
<%= form_with(model: @room, local: true) do |form| %>

  <div class="field">
    <%= form.label :施設名%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :施設詳細 %>
    <%= form.text_area :introduction %>
  </div>

  <div class="field">
    <%= form.label :料金 %>
    <%= form.number_field :price %>
  </div>
  <div class="field">
    <%= form.label :住所 %>
    <%= form.text_field :address %>
  </div>
  <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "form-control" %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to '戻る', rooms_path %>

app/views/rooms/index.html.erb
<h1>施設一覧</h1>
<table>
  <thead>
    <tr>
      <th>施設画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>宿泊料金（/日）</th>
      <th>作成日</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <td>
    <% if room.image? %>
      <%= image_tag room.image.url, width: 200 %>
    <% else %>
      <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png' %>
    <% end %>
    <!-- 他のテーブルのデータ表示 -->
      </td>
      <td><%= link_to room.name, room_path(room) %></td>
      <td><%= room.introduction %></td>
      <td><%= room.price %>円</td>
      <td><%= room.created_at.strftime('%Y-%m-%d') %></td>
      <td><%= link_to '編集', edit_room_path(room) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h1>施設作成</h1>
<%= render 'layouts/error_messages', model: @room %>
<%= form_with(model: @room, local: true) do |form| %>

  <div class="field">
    <%= form.label :施設名%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :施設詳細 %>
    <%= form.text_area :introduction %>
  </div>

  <div class="field">
    <%= form.label :料金 %>
    <%= form.number_field :price %>
  </div>
  <div class="field">
    <%= form.label :住所 %>
    <%= form.text_field :address %>
  </div>
  <div class="form-group">
    <%= form.label :部屋画像 %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
 <%= form.hidden_field :user_id, value: @user.id %>
 <%= form.hidden_field :room_id, value: @room.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/search.html.erb
<div class = "search" > 
    <h1>検索結果：<%= @results.count %>件</h1>

    <div class = "search_base" >
        <% @results.each do |results| %>
                    <div class = "search_room" >
                        <h1>施設名<%= results.name %></h1>
                        <h4>施設詳細:<%= results.introduction %></h4>
                        <h4>エリア名：<%= results.address %></h4>
                        <h4>金額：<%= results.price %>円</h4>
                        <h4><%= link_to "詳細を見る", room_path(results) %></h4>
                    </div>
            </div>
        <% end %>
    </div>
    <a href="javascript:history.back()">[戻る]</a>
</div>

app/views/rooms/show.html.erb
 <% if @room.image?  %>
      <%= image_tag @room.image.url  %>
    <% else %>
      <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png' %>
    <% end %>

<div>
  <h1 class="hotel-name">
    <%= @room.name %>
  </h1>
</div>
<div class="introduction">
  <%= @room.introduction %>
</div>
<div class="price">
  宿泊料金： <%= @room.price %>円/日
</div>
<%= notice %>
<%= alert %>
<%= form_with model: @reservation, url: confirm_reservation_path, method: :post do |f| %>
<%= render 'layouts/error_messages', model: @reservation %>
  <table>
    <tr>
      <th><%= f.label :check_in, "チェックイン" %></th>
      <td><%= f.date_field :check_in %></td>
    </tr>

    <tr>
      <th><%= f.label :check_out, "チェックアウト" %></th>
      <td><%= f.date_field :check_out %></td>
    </tr>

    <tr>
      <th><%= f.label :number_of_people, "人数" %></th>
      <td><%= f.text_field :number_of_people %></td>
    </tr>

    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :room_id, value: @room.id %>
  </table>

  <%= f.submit "登録する" %>
<% end %>

<%= link_to '戻る', new_room_path, class: "back-link" %>