config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"
  get '/account', to: 'account#show'
  get '/reservations/confirm', to: 'reservations#index'
  resources :reservations
  resources :rooms do
    collection do
      get 'search', to: 'rooms#search'
    end
  end
  devise_for :users
  resources :rooms
  get 'accounts/show'
  resources :users
  resource :account, only: [:edit, :update, :show]
  get '/account', to: 'accounts#show'
  get '/users', to: 'users#show'
  get '/rooms', to: 'rooms#new'
  post '/rooms', to: 'rooms#update'
  get '/reservations/confirm', to: 'reservations#confirm', as: 'confirm_reservation'
  post '/reservations/confirm', to: 'reservations#confirm'
  get '/rooms/search', to: 'rooms#search'

  resources :reservations, only: [:index, :new, :create, :show] do
    collection do
      post 'confirm'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :reserves
    has_many :rooms 
    def self.ransackable_attributes(auth_object = nil)
        %w[name introduction address created_at updated_at]
      end
    
      def self.ransackable_associations(auth_object = nil)
        %w[reserves rooms]
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index

    @posts = Post.all
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:room).order("created_at desc")
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def search
    binding.pry
    @user = current_user
    @q = Room.ransack(params[:q])
    binding.pry
    @rooms = @q.result(distinct: true)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :email, :password_digest)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!doctype html>
<html lang="ja">
 
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 
    <title>Hello, world!</title>
</head>
 

<body>
<header>
  <% if user_signed_in? %>
    <!-- ユーザーがログインしていた時の処理 -->
    <div class="dropdown ml-auto">
      <div class="d-flex align-items-center">
        <h5 class="mr-2">アイコン画像</h5>
        <div class="icon">
          <% if current_user.avatar? %>
            <%= image_tag current_user.avatar.url, size: '70x70' %>
          <% else %>
            <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png' %>
          <% end %>
        </div>
      </div>
      <a class="dropdown-toggle" href="#" id="user-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <h5 class="ml-2 mr-3"> 名前 </h5>
        <%= current_user.name %>
      </a>
      <div class="dropdown-menu" aria-labelledby="user-dropdown">
        <%= link_to "プロフィール", user_path(current_user), class: 'dropdown-item' %>
        <%= link_to "予約一覧", reservations_path, class: 'dropdown-item' %> 
        <%= link_to "部屋一覧", rooms_path, class: 'dropdown-item' %>
        <%= link_to 'アカウント', account_path, class: 'dropdown-item' %>
        <%= link_to '施設新規登録', new_room_path, class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
</header>

 

<div class = "search_index">
<h4>キーワード検索</h4>          
<%= search_form_for @q, url: search_rooms_path do |f| %>
  <%= f.label :name_or_introduction_cont ,"キーワード" %>
  <%= f.search_field :name_or_introduction_cont %>
  <%= f.submit "検索", class: "search-button" %>
<% end %>
<h4>住所検索</h4>
<%= search_form_for @q, url: search_rooms_path do |f| %>
  <%= f.label :address_cont, '住所' %>
  <%= f.search_field :address_cont %>
  <%= f.submit '検索' %>
<% end %>
</div>

</div>
</div>

<div class = "all_spots">

<div class="item-container">
  <div class="item"> 
    <div class="spot">    
      <span>東京</span>
      <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/tokyo.jpg", size: "100x100"), search_rooms_path(q: { address_cont: "東京" }) %>
    </div>
  </div>

  <div class="item"> 
    <div class="spot">  
      <span>大阪</span>
      <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/osaka.jpg", size: "100x100"), search_rooms_path(q: { address_cont: "大阪" }) %>
    </div>
  </div>

  <div class="item"> 
    <div class="spot">
      <span>京都</span>
      <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/kyoto.jpg", size: "100x100"), search_rooms_path(q: { address_cont: "京都" }) %>
    </div>  
  </div>

  <div class="item"> 
    <div class="spot">
      <span>札幌</span>
      <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/sapporo.jpg", size: "100x100"), search_rooms_path(q: { address_cont: "札幌" }) %>
    </div>          
  </div>
</div>
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
<header>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %>
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
</header>




<h4> ポテパンキャンプ　宿泊アプリ　</h4>


<% end %>
</header>
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @post.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @post.password_digest %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>